PN_Expert/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from PN_Expert import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lk.urls'), name='home'),
    path('', include('push_notifications.urls'), name='push'),
    path('', include('diagnostic.urls'), name='diagnostic'),
    path('', include('survey.urls'), name='survey'),
    path('', include('pills.urls'), name='pills'),
    path('', include('sheduling.urls'), name='sheduling'),
    path('video/', include('video_proc.urls'), name='videos'),
    url(r'^email-verification/$',
        TemplateView.as_view(template_name="email_verification.html"),
        name='email-verification'),
    url(r'^password-reset/$',
        TemplateView.as_view(template_name="password_reset.html"),
        name='password-reset'),
    url(r'^password-reset/confirm/$',
        TemplateView.as_view(template_name="password_reset_confirm.html"),
        name='password-reset-confirm'),

    url(r'^user-details/$',
        TemplateView.as_view(template_name="user_details.html"),
        name='user-details'),
    url(r'^password-change/$',
        TemplateView.as_view(template_name="password_change.html"),
        name='password-change'),

    # this url is used to generate email content
    url(r'^password-reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        TemplateView.as_view(template_name="password_reset_confirm.html"),
        name='password_reset_confirm'),

    url(r'^rest-auth/', include('rest_auth.urls')),
    url(r'^rest-auth/registration/', include('rest_auth.registration.urls')),
    url(r'^account/', include('allauth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lk/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('<slug:slug>', views.profile, name='profile_detail'),
    path('account/', views.account, name='account'),
    path('account/update/', views.update_params, name='api_update_params'),
    path('api/diary/get/', views.get_diary_list, name='api_diary'),
    path('api/diary/create/', views.create_diary_rec, name='create_diary'),
    path('accounts/login/', views.main_redirect_view, name='main_redirect'),
    path('news/', views.news_list, name='news_list'),
    path('api/profile/get/', views.get_user_info, name='profile_info'),
    path("api/profile/avatar/", views.UserAvatarUpload.as_view(), name="rest_user_avatar_upload"),
    path('api/profile/update/', views.write_user_info, name='profile_info_write'),
    path('api/profile/flags/', views.set_user_flags, name='set_user_flags'),
    path('api/steps/create/', views.create_steps, name='create_steps'),
    path('api/steps/get/', views.get_steps, name='get_steps'),
    path('api/user/id/', views.get_user_id, name='get_id_by_email'),
    path('api/hads/depression/', views.get_depression, name='get_depression'),
    path('api/hads/alarm/', views.get_alarm, name='get_alarm'),
    path('api/smiles/', views.get_smiles, name='get_smiles'),
    path('api/search/user/', views.search_user, name='search_user'),
    path('api/search/user/doctor/', views.search_user_doctor, name='search_doctor'),
    path('api/search/user/relative/', views.search_user_relative, name='search_rel'),
    path('api/profile/doctor/set/', views.connect_patient_to_arzt, name='set_doctor'),
    path('api/profile/doctor/get/', views.get_current_doctor, name='get_doctor'),
    path('api/profile/doctor/detach/', views.detach_arzt, name='detach_doctor'),
    path('api/game/memory/create/', views.create_mem_stats, name='create_mem'),
    path('api/game/reaction/create/', views.create_react_stats, name='create_react'),
    path('api/game/memory/get/', views.get_memory_stats, name='get_mem'),
    path('api/game/reaction/get/', views.get_reaction_stats, name='get_react'),
    path('api/schwabe/get/', views.get_schwabe, name='get_schwabe'),
    path('api/pdq/get/', views.get_PDQ_39, name='get_pdq'),
    path('api/UPDRS/get/', views.get_UPDRS_stats, name='get_updrs'),
    path('api/daily_activity/get/', views.get_daily_activity, name='get_daily'),
    path('api/profile/relative/set/', views.connect_patient_to_relative, name='set_rel'),
    path('api/profile/relative/get/', views.get_current_relative, name='get_rel'),
    path('api/profile/relative/detach/', views.detach_relative, name='detach_rel'),
]

lk/models.py
import datetime
import uuid

from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
from multiselectfield import MultiSelectField

from diagnostic.models import Event, StartEvent, StartShedule, MessageShedule
from sheduling.models import MessageSurvey, SurveyShedule
from video_proc.decorators import postpone

TEST = False

GENDER = (
    (0, "MALE"),
    (1, "FEMALE")
)

STATUS = (
    (0, "Пациент"),
    (1, "Врач"),
    (2, "Родственник"),
)

TIMESHIFT = (
    (-1, ' MSK−1'),
    (0, 'MSK'),
    (1, 'MSK+1'),
    (2, 'MSK+2'),
    (3, 'MSK+3'),
    (4, 'MSK+4'),
    (5, 'MSK+5'),
    (6, 'MSK+6'),
    (7, 'MSK+7'),
    (8, 'MSK+8'),
    (9, 'MSK+9'),
)

PUSH_DELAY = (
    (0, '1 час'),
    (1, '3 часа'),
    (2, '5 часов'),
    (3, '7 часов')
)


def generate_pin_string():
    return uuid.uuid4().hex[:6].upper()


class UserProfile(models.Model):
    """
    Extended user model
    """
    # Ссылка на объект пользователя
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # Имя
    name = models.CharField(max_length=50, blank=True)
    # Фамилия
    vorname = models.CharField(max_length=50, blank=True)
    # Отчество
    fathername = models.CharField(max_length=50, blank=True)
    gender = models.IntegerField(choices=GENDER, default=0)
    age = models.DateField(default=datetime.date(2000, 1, 1))
    parkinson = models.DateField(default=datetime.date(2000, 1, 1))
    # Статус в проекте — врач, пациент, тестировщик...
    status = models.IntegerField(choices=STATUS, default=0)
    # Опыт
    exp = models.IntegerField(default=0)
    # Флаг, показывающий, заполненна ли основная инфа.
    isPrimaryInfo = models.BooleanField(default=False)
    # Флаг, указывающий на заполненные дополнительные поля
    isFull = models.BooleanField(default=False)
    isDiary = models.BooleanField(default=False)
    isSurvey1 = models.BooleanField(default=False)
    isSurvey2 = models.BooleanField(default=False)
    isSurvey0 = models.BooleanField(default=False)
    isStatus = models.BooleanField(default=False)
    isPills = models.BooleanField(default=False)
    isSick = models.BooleanField(default=False)
    isHospitalInfo = models.BooleanField(default=False)
    # Для врача:
    hospital = models.TextField(default="")
    position = models.TextField(default="")
    # Город проживания
    city = models.CharField(max_length=50, blank=True)
    # URL на личную страницу
    slug = models.SlugField(null=True)
    # Флаг блокаировки врача
    isBlocked = models.BooleanField(default=False)
    # PIN for patients
    pincode = models.TextField(default=generate_pin_string, max_length=10)
    # Link to doctor account
    doctor = models.ForeignKey(User, on_delete=models.CASCADE, related_name='doctor', default=1, null=True)
    # Link to relative
    relative = models.ForeignKey(User, on_delete=models.CASCADE, related_name='relative', default=1, null=True)
    # Avatar
    avatar = models.ImageField(upload_to="avatars", default="lk/static/images/noimg.jpg")
    timeshift = models.IntegerField(choices=TIMESHIFT, default=0)
    send_push = models.BooleanField(default=True)
    reminders = models.IntegerField(choices=PUSH_DELAY, default=1)

    def __str__(self):
        return "%s's profile" % self.user

    def get_absolute_url(self):
        """
        Makes slug
        :return: absolute url with slug
        """
        return reverse('profile_detail', kwargs={'slug': self.slug})


def create_user_profile(sender, instance, created, **kwargs):
    """
    This function will create UserProfile parallel with new User
    :param sender: NOT_USED
    :param instance: User object
    :param created: NOT_USED
    :param kwargs: User args
    :return:
    """
    if created:
        profile, created = UserProfile.objects.get_or_create(user=instance)
        profile.slug = slugify(profile.user.get_username())
        if profile.status == 1:
            profile.isBlocked = True
        profile.save()
        if TEST:
            Event.objects.create(description="Снимок в полный рост",
                                 summary="Снять себя в полный рост на хорошую камеру",
                                 location="SPB",
                                 end=datetime.datetime.now() + datetime.timedelta(hours=5),
                                 user=instance,
                                 event_type=3)
            Event.objects.create(description="Пройти тест",
                                 summary="Пройти тест 'Сложные виды поведения'",
                                 location="SPB",
                                 end=datetime.datetime.now() + datetime.timedelta(hours=5),
                                 user=instance,
                                 survey_pk=2,
                                 event_type=4)
            Event.objects.create(description="Загрузить историю болезни",
                                 summary="Загрузить файл в раздел загрузки",
                                 location="SPB",
                                 end=datetime.datetime.now() + datetime.timedelta(hours=5),
                                 user=instance,
                                 survey_pk=2,
                                 event_type=0)
        else:
            create_events(instance, profile)


DEPRESSION = (
    (0, "«норма» (отсутствие достоверно выраженных симптомов тревоги и депрессии)"),
    (1, "«субклинически выраженная тревога / депрессия»"),
    (2, "«клинически выраженная тревога / депрессия»")
)

ALARM = (
    (0, '«норма» (отсутствие достоверно выраженных симптомов тревоги и депрессии)'),
    (1, "«субклинически выраженная тревога / депрессия»"),
    (2, "«клинически выраженная тревога / депрессия»")
)


class HADS_Result(models.Model):
    """
    Class with HADS test result
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    day = models.DateField(default=timezone.now)
    depression = models.IntegerField(choices=DEPRESSION, default=0)
    value = models.IntegerField(default=0)


class ReactionStatistics(models.Model):
    """
    Reaction statistics with reaction time for sniper game
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    day = models.DateField(default=timezone.now)
    time = models.FloatField(default=0)
    move = models.FloatField(default=0)

    def __str__(self):
        return "Статистика игры `снайпер` для пользователя " + self.user.username + \
               ", дата " + str(self.day)


class MemoryStatistics(models.Model):
    """
    Reaction statistics with reaction time for sniper game
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    day = models.DateField(default=timezone.now)
    turn = models.FloatField(default=0)
    pairs = models.FloatField(default=0)

    def __str__(self):
        return "Статистика игры `карточки` для пользователя " + self.user.username + \
               ", дата " + str(self.day)


class HADS_Alarm(models.Model):
    """
    Class with HADS test result
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    day = models.DateField(default=timezone.now)
    alarm = models.IntegerField(choices=ALARM, default=0)
    value = models.IntegerField(default=0)


class SmileStats(models.Model):
    """
    Smile statistics
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    day = models.DateField(default=timezone.now)
    value = models.IntegerField(default=0)


class UPDRSStats(models.Model):
    """
    UPDRS answer stats
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    day = models.DateField(default=timezone.now)
    cognitive = models.FloatField(default=0)
    gallutination = models.FloatField(default=0)
    depression = models.FloatField(default=0)
    danger = models.FloatField(default=0)
    apation = models.FloatField(default=0)
    dofamin = models.FloatField(default=0)
    sleep = models.FloatField(default=0)
    day_sleep = models.FloatField(default=0)
    pain = models.FloatField(default=0)
    urina = models.FloatField(default=0)
    kal = models.FloatField(default=0)
    helicopters = models.FloatField(default=0)
    tired = models.FloatField(default=0)

    speak = models.FloatField(default=0)
    eat_liquid = models.FloatField(default=0)
    jummy = models.FloatField(default=0)
    eating = models.FloatField(default=0)
    dressing = models.FloatField(default=0)
    hyhien = models.FloatField(default=0)
    writing = models.FloatField(default=0)
    hobby = models.FloatField(default=0)
    bed = models.FloatField(default=0)
    tremor = models.FloatField(default=0)
    standup = models.FloatField(default=0)
    going = models.FloatField(default=0)
    freezing = models.FloatField(default=0)

    discinesing = models.FloatField(default=0)
    disc_f = models.FloatField(default=0)
    off_time = models.FloatField(default=0)
    fluctuation = models.FloatField(default=0)
    flucation_difficulty = models.FloatField(default=0)
    distony = models.FloatField(default=0)


class DailyActivityStats(models.Model):
    """
    Daily activity stats
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    day = models.DateField(default=timezone.now)
    sleep_time = models.FloatField(default=0)
    no_hom_time = models.FloatField(default=0)
    work_time = models.FloatField(default=0)
    sport_time = models.FloatField(default=0)


class ShwabStats(models.Model):
    """
    Schwab&England stats
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    day = models.DateField(default=timezone.now)
    value = models.IntegerField(default=0)


class PDQ39Stats(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    day = models.DateField(default=timezone.now)
    value = models.IntegerField(default=0)


@postpone

lk/forms.py
from django import forms
from django.core.files.images import get_image_dimensions

from .models import UserProfile


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['name', 'vorname', 'fathername', 'gender', 'age', 'status', 'city', 'avatar']

    def clean_avatar(self):
        avatar = self.cleaned_data['avatar']

        try:
            w, h = get_image_dimensions(avatar)

            # validate dimensions
            max_width = max_height = 2000
            if w > max_width or h > max_height:
                raise forms.ValidationError(
                    u'Please use an image that is '
                    '%s x %s pixels or smaller.' % (max_width, max_height))

            # validate content type
            main, sub = avatar.content_type.split('/')
            if not (main == 'image' and sub in ['jpeg', 'pjpeg', 'gif', 'png']):
                raise forms.ValidationError(u'Please use a JPEG, '
                                            'GIF or PNG image.')

            # validate file size
            # if len(avatar) > (20 * 1024):
            #     raise forms.ValidationError(
            #         u'Avatar file size may not exceed 20k.')

        except AttributeError:
            """
            Handles case when we are updating the user profile
            and do not supply a new avatar
            """
            pass
        return avatar

lk/templates/account_c.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Профиль</title>

    <!-- <link rel="stylesheet" href="{% static 'css/common.css' %}" />
	<link rel="stylesheet" href="{% static 'css/style_account.css' %}" /> -->
    <!-- <link rel="stylesheet" href="{% static 'css/materialize.css' %}" />	 -->
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}  ?ver=2" />	 -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style-profile.css' %}  ?ver=2"/>

    <link rel="icon" href="images/logo-icon.ico">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
<div id="menu-section">
    <div id="logo">
        <img src="{% static 'images/logo-icon.svg' %}" alt="">
        <p>TREMORO</p>
    </div>


    <div id="menu">
        <a href="{% url 'account' %}" class="waves-effect waves-dark menu-entry selected"><i
                class="material-icons left selected">account_circle</i>Аккаунт</a>
        <a href="" class="waves-effect waves-dark menu-entry"><i class="material-icons left ">dashboard</i>Новости</a>
        <a href="profile.html" class="waves-effect waves-dark menu-entry"><i class="material-icons left">date_range</i>Активности</a>
        <a href="profile.html" class="waves-effect waves-dark menu-entry"><i class="material-icons left">supervisor_account</i>Пользователи</a>
        <a href="profile.html" class="waves-effect waves-dark menu-entry"><i
                class="material-icons left">favorite_border</i>О нас</a>
        <a href="profile.html" class="waves-effect waves-dark menu-entry"><i class="material-icons left">settings</i>Настройки</a>
    </div>

    <div id="join-button-space">
        <button class="btn-large waves-effect waves-light">Присоединиться</button>
    </div>

</div>


<div class="container" style="width:100%; max-width: 100%; margin: 0%">
    <div class="row">
        <div class="col s12 m4 l4 first-column">
            <div class="row valign-wrapper center">
                <div class="col s12">
                    <h5>ЛичaDWadый кабинет</h5>
                </div>
            </div>
            <div class="row valign-wrapper center">
                <div class="col s12">
                    <img src="{% static 'images/noimg.jpg' %}" alt="Profile Photo" class="circle responsive-img">
                </div>
            </div>
            <div class="row valign-wrapper center">
                <div class="col s12">
                    <p>Имя Фамилия</p>
                </div>
            </div>
            <div class="row valign-wrapper center">
                <div class="col s12">
                    <p>Статус (врач)</p>
                </div>
            </div>
        </div>

        <div class="col s12 m8 l8 second-column">
            <div class="row valign-wrapper">
                <div class="col s12">
                    <h5>Подробная информация</h5>
                </div>
            </div>
            <div class="row valign-wrapper">
                <div class="col s12">
                    <div class="row">
                        <form class="col s12">
                            <div class="row">
                                <div class="input-field col s12 m4 l4">
                                    <input value="{{ name }}" id="surname" type="text" class="validate" tabindex="1">
                                    <label for="surname">Фамилия</label>
                                </div>
                                <div class="input-field col s12 m4 l4">
                                    <input value="{{ vorname }}" id="name" type="text" class="validate" tabindex="2">
                                    <label for="name">Имя</label>
                                </div>
                                <div class="input-field col s12 m4 l4">
                                    <input value="{{ fname }}" id="patronym" type="text" class="validate" tabindex="3">
                                    <label for="patronym">Отчество</label>
                                </div>

                                <div class="input-field col s6 m4">
                                    <input id="id_age" name="age" tabindex="4" type="text" class="col datepicker"
                                           placeholder="Дата рождения">
                                    <label for="id_age">Дата рождения:</label>
                                </div>

                                <div class="input-field col s6 m4">
                                    <input id="id_city" name="city" tabindex="5" type="text" class="validate"
                                           placeholder="Город проживания">
                                    <label for="id_city">Город проживания:</label>
                                </div>

                                <div class="col s12 m4">
                                    <label for="id_gender">Пол:</label>
                                    <p>
                                        <label>
                                            <input value="0" type="radio" name="gender" id="id_gender" tabindex="5"
                                                   checked/>
                                            <span>Мужской</span>
                                        </label>
                                    </p>
                                    <p>
                                        <label>
                                            <input name="gender" value="1" tabindex="6" id="id_gender" type="radio"/>
                                            <span>Женский</span>
                                        </label>
                                    </p>
                                </div>
                                <!-- <div class="input-field col s6 m6">
                                    <input id="email_inline" type="email" class="validate">
                                    <label for="email_inline">Email</label>
                                    <span class="helper-text" data-error="wrong" data-success="right">Helper text</span>
                                </div> -->

                                <div class="input-field col s12 m6">
                                    <select>
                                        <option value="" disabled selected>Роль в проекте</option>
                                        <option value="1">Пациент</option>
                                        <option value="2">Родственник</option>
                                        <option value="3">Врач</option>
                                        <option value="4">Тестировщик</option>
                                        <option value="3">Исследователь</option>
                                    </select>
                                    <label>Роль в проекте</label>
                                </div>

                                <div class="input-field col s12">
                                    <span>Далее необходимо указать Вашу роль в данном проекте. Если Вы являетесь пациентом, родственником или врачом, то Вам необходимо подтвердить вашу роль. Для этого внесите в следующее поле персональный код, выданный администратором.</span>
                                </div>


                                <!-- <div class="input-field col s6">
                                  <input id="last_name" type="text" class="validate">
                                  <label for="last_name">Last Name</label>
                                </div> -->
                            </div>

                            <div class="row">
                                <div class="input-field col s12">
                                    <input id="password" type="password" class="validate">
                                    <label for="password">Password</label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s12">
                                    <input id="email" type="email" class="validate">
                                    <label for="email">Email</label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col s12">
                                    This is an inline input field:
                                    <div class="input-field inline">
                                        <input id="email_inline" type="email" class="validate">
                                        <label for="email_inline">Email</label>
                                        <span class="helper-text" data-error="wrong"
                                              data-success="right">Helper text</span>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- <div class="section " id="user-profile">
			<div class="card-panel hoverable">
				<div class="row marg">
				<div class="col s12 m7">
					<div class="display-flex media ">
						<div class="col s12 m3">
							<img src="{{avatar}}" alt="users view avatar"
							height="80px" width="80px">
						</div>
						<div class="col s12 m9">
							<div class="media-body">
								<h6 class="media-heading">
								<span class="users-view-name">{{name}}</span>
								<span class="grey-text">@</span>
								<span class="users-view-username grey-text">{{user.username}}</span>
								<blockquote  >
									По всем вопросам пишите в личные сообщения :)
								</blockquote>
								</h6>
							</div>
						</div>
					</div>
				</div>
				<div class="col s12 m5 quick-action-btns display-flex justify-content-end align-items-center pt-2">
					<a href="app-email.html" class="btn-large btn-light-indigo right-align waves-light waves-effect"><i class="material-icons">mail_outline</i></a>
					{% if not isFull %}
					<a href="/accounts/changeform" class="btn-large indigo">Обновить данные</a>
					{% endif %}
				</div>
				</div>
			</div>
			<div class="card ">
				<div class="card-content hoverable">
				<div class="row indigo lighten-5 border-radius-4 mb-2">
					<div class="col s12 m12 users-view-timeline">
					<h6 class="indigo-text m-0">ФИО: <span>{{vorname}} {{name}} {{fname}}</span></h6>
					</div>
				</div>
				<div class="row">
					<div class="col s12">
					<table class="striped">
						<tbody>


						</tbody>
					</table>
					<h6 class="mb-2 mt-2"><i class="material-icons">error_outline</i> Personal Info</h6>
					<table class="striped">
						<tbody>
							<tr>
								<td>Должность:</td>
								<td>{{position}}</td>
							</tr>
							<tr>
								<td>E-mail:</td>
								<td class="users-view-email">{{ email }}</td>
							</tr>
							<tr>
								<td>Стаж</td>
								<td class="users-view-name">{{exp}}</td>
							</tr>

							<tr>
								<td>Username:</td>
								<td class="users-view-username">{{user.username}}</td>
							</tr>

							<tr>
								<td>День рождения:</td>
								<td>{{bdate}}</td>
							</tr>
							<tr>
								<td>Возраст</td>
								<td class="users-view-age">{{age}}</td>
							</tr>								


						</tbody>
					</table>
						<h6 class="mb-2 mt-2"><i class="material-icons">link</i> Social Links</h6>
						<table class="striped">
							<tbody>
							<tr>
								<td>Facebook:</td>
								<td><a href="#">https://www.facebook.com/</a></td>
							</tr>
							<tr>
								<td>Instagram:</td>
								<td><a href="#">https://www.instagram.com/</a></td>
							</tr>
							</tbody>

					</table>
					</div>
				</div>
				</div>
			</div>
		</div>
	</div>
	<div class="hat white-text row" style="margin-bottom: 0em;">
		<div class="container m3 s12 center" style="padding: 1em;">
			<h6>© 2020 NTI THEORMECH_RELEASE</h6>
		</div>
	</div> -->


<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<script src="{% static 'js/materialize.min.js' %}"></script>
<script src="{% static '/js/registerSw.js' %}"></script>

<script>
    document.addEventListener('DOMContentLoaded', e => {
        let tabElements = document.querySelectorAll('.tabs');
        let result = M.Tabs.init(tabElements, {});

        let datepickers = document.querySelectorAll('.datepicker');
        result = M.Datepicker.init(datepickers, {
            format: 'yyyy-mm-dd'
        })
    })
</script>

<script>
    $(document).ready(function () {
        $('select').formSelect();
    });
</script>


</body>
</html>

lk/templates/base.html
{% load static %}
{% csrf_token %}

<!DOCTYPE html>
<html>
<head>
    {% block content %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="one-more-city">

    <title>Заходи, не стесняйся</title>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- <link rel="stylesheet" href="{% static 'css/materialize/materialize.css' %}" /> -->

    <!-- <link rel="stylesheet" type="text/css" href="{% static 'css/only-size.css' %}  ?ver=2" /> -->
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'css/main-for-all-page.css' %}  ?ver=2" /> -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script> -->
    <script src="{% static 'js/materialize.min.js' %}"></script>
    {% endblock %}
    {% load i18n %}
    {% load account socialaccount %}
</head>

<body>
<!--  -->


<!--  -->
</body>
</html>

lk/templates/email_verification.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <h3>E-mail verification</h3>
        <hr/>
        {% include "fragments/email_verification_form.html" %}
    </div>
{% endblock %}

lk/templates/news.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>NEWS</title>
</head>
<body>
Типа нововсти:
{% for recording in recordings %}
    <br>
    {{ recording.header }}
    {{ recording.text }}
    {{ recording.published }}
    <br>
{% endfor %}

</body>
</html>

lk/templates/password_reset.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <h3>Password reset</h3>
        <hr/>
        {% include "fragments/password_reset_form.html" %}
    </div>
{% endblock %}

lk/templates/password_reset_confirm.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <h3>Password reset confirmation</h3>
        <hr/>
        {% include "fragments/password_reset_confirm_form.html" %}
    </div>
{% endblock %}



{% block script %}
    <script type="text/javascript">
        var url_elements = window.location.pathname.split('/');
        if (url_elements.length == 6) {
            var uid = url_elements[url_elements.length - 3];
            if (uid !== undefined) {
                $('input[name=uid]').val(uid);
            }
            var token = url_elements[url_elements.length - 2];
            if (token !== undefined) {
                $('input[name=token]').val(token);
            }
        }
    </script>
{% endblock %}